// Generated by CoffeeScript 1.7.1
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

window.App = (function(_super) {
  __extends(App, _super);

  function App() {
    this.adjustScore = __bind(this.adjustScore, this);
    this.dealHand = __bind(this.dealHand, this);
    return App.__super__.constructor.apply(this, arguments);
  }

  App.prototype.initialize = function() {
    var deck;
    this.set('myScore', 0);
    this.set('money', 100);
    this.set('bet', 5);
    this.set('dealerScore', 0);
    this.set('deck', deck = new Deck());
    return this.dealHand();
  };

  App.prototype.dealHand = function() {
    this.set('playerHand', this.get('deck').dealPlayer());
    this.set('dealerHand', this.get('deck').dealDealer());
    this.get('playerHand').on('flipCard', (function(_this) {
      return function() {
        return _this.get('dealerHand').models[0].flip();
      };
    })(this));
    return this.get('playerHand').on('checkWinner', (function(_this) {
      return function() {
        var dealerScore, playerScore;
        playerScore = _this.getScore(_this.get('playerHand').scores());
        dealerScore = _this.getScore(_this.get('dealerHand').scores());
        if (playerScore <= 21 && playerScore > dealerScore) {
          _this.set('myScore', _this.get('myScore') + 1);
          _this.adjustScore('win');
        } else {
          _this.set('dealerScore', _this.get('dealerScore') + 1);
          _this.adjustScore('lose');
        }
        return setTimeout((function() {
          return _this.dealHand();
        }), 2000);
      };
    })(this));
  };

  App.prototype.getScore = function(scores) {
    if (scores.length === 1) {
      return scores[0];
    } else if (scores[1] > 21) {
      return scores[0];
    } else {
      return scores[1];
    }
  };

  App.prototype.adjustScore = function(outcome) {
    if (outcome === 'win') {
      this.set('money', (this.get('money')) + (this.get('bet')));
      return this.set('bet', 5);
    } else {
      this.set('money', (this.get('money')) - (this.get('bet')));
      this.set('bet', 5);
      if ((this.get('money')) === 0) {
        return this.trigger('noMoney');
      }
    }
  };

  return App;

})(Backbone.Model);
